services:
  frontend:
    container_name: sasca_frontend
    image: scr.stemsi.cloud/sasca-frontend:latest
    ports:
      - "9895:3000"
    env_file:
      - .env.frontend
    networks:
      - sasca_public_network
  
  backend:
    container_name: sasca_backend
    image: scr.stemsi.cloud/sasca-backend:latest
    env_file:
      - .env.backend
    volumes:
      - ./samples:/app/samples:rw
    networks:
      - sasca_core_network
      - sasca_public_network

  db:
    container_name: sasca_db
    image: postgres:16
    ports:
      -"DBPORT:5432"
    env_file:
      - .env.db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - sasca_core_network

networks:
  sasca_public_network:
    driver: bridge

  sasca_core_network:
    driver: bridge