import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import UserProvider from "@/providers/UserProvider";
import BottomModal from "@/components/BottomModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SASCA - Student",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider strict={true} allowedRoles={['student']}>
          {children}
          <BottomModal />
        </UserProvider>
      </body>
    </html>
  );
}
